### ISSUE TITLE
cant build this kernel

### ISSUE THREAD

**Issue by FOSSBOSS** [embeddedarm/linux-3.14.28-imx28#5]
I get errors when trying to build this kernel, 
but I get stuck around the time this error occurs:
usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of 'yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here

in the file ./linux-rtk/scripts/dtc/dtc-lexer-lex.c

I edited: 'YYLTYPE yylloc' to 'extern YYLTYPE yylloc'
which got me incrementally further, but now there are other errors I dont have a clue about fixing.

dtc-lexer.l:43:22: error: expected ‘;’ before ‘static’

......

dtc-lexer.lex.c: In function ‘yylex’:

dtc-lexer.l:47:18: error: ‘yylloc’ undeclared (first use in this function); did you mean ‘yyalloc’?

**Comment by cargoudel** [comment]
Try an older version of gcc.

**Comment by markfeathers** [comment]
This happens from your systems libdtc symbols leaking into the kernel build process which causes multiple definitions. If you remove this libdtc from your host system, that will prevent the multiple definitions. That is probably the most straightforward path for you.

Newer kernels have fixed this, and if you are able to resolve this with a merge request I'd happily pull it.

Even besides this issue we've had weird breaks in the past from things like make versions, perl versions, and other small breaks when building on a newer system than the kernel was targeting. This sort of issue is why I'm now documenting to use Docker/podman for kernel build environments. For example:
https://docs.embeddedts.com/TS-7250-V3#Debian_10_-_Cross_Compiling
I have this set up for most of our kernels internally, but I didn't think it made sense to change the public documentation for older series.  You could try this as well:
https://files.embeddedts.com/~mark/Customers/ts76xx_docker_kernel.tar.bz2
Run the build-kernel.sh script and it will set up a docker, clone the kernel in that directory, and compile with the toolchain it sets up for that docker, and output a kernel.tar.bz2 with the new build.  You can also ./build-kernel make menuconfig to get into the options.  The upside to this is it doesn't matter what host distribution you're using, and this should continue to work pretty much forever.

**Comment by FOSSBOSS** [comment]
Neat, the script from (https://files.embeddedts.com/~mark/Customers/ts76xx_docker_kernel.tar.bz2
runs, but during the process of Make:
cp: cannot stat 'arch/arm/boot/uImage': No such file or directory
cp: cannot stat 'arch/arm/boot/dts/imx28-*.dtb': No such file or directory
 uImage isnt there. 
 in 'arch/arm/boot/dts/, there are no imx28-*.dtb files, but there are mx28-*.dts files.
 is that what should be used? 
 _lines in question from build-kernel.sh_
 cp arch/arm/boot/uImage  "$TEMPDIR"/boot/uImage
cp arch/arm/boot/dts/imx28-*.dtb "$TEMPDIR"/boot/

**Comment by ts-kris** [comment]
Apologies for the delay in responding to this.

We're not quite sure why the yylloc error was showing up, but I was indeed able to observe it on an Ubuntu 22.04 installation. In reviewing some changes and similar errors other people have observed I've found the best way to work around this is to make a slight change to the dtc lexer tools that allows them to cleanly build.

Note that, as @markfeathers hinted, we've observed some issues with a host libfdt interfering with builds, but only on some distributions. I was unable to observe a link between having libfdt installed on the host and build failures/successes.

I've tested the patch on Ubuntu 22.04 and Debian Stretch (the distribution that was originally used for building that kernel and creating the documentation) and it succeeded on both.

Please pull in the changes and re-run through the build instructions as outlined in the product manual. Be sure to run a `make mrproper` before re-running any of the other make commands to ensure the whole tree has been cleaned. Let me  know if you continue to run in to issues.

**Comment by FOSSBOSS** [comment]
Well, I ran through compiling, and installing bootlets, but the OS still
reports uname -a as kernel 2.6.
I started looing at uImage and zImage. I verified I have the 256MB ram
version with
cat /proc/meminfo
MemTotal:         256024 kB

So then I looked at the zImage strings for the zImage i wrote to the
sdCard.
$strings zImage | less
-- System halted
Attempting division by 0!
stack-protector: Kernel stack is corrupted
Uncompressing Linux...
decompressor returned an error
 done, booting the kernel.
invalid distance too far back
invalid distance code
invalid literal/length code
incorrect header check
unknown compression method
invalid window size
invalid block type
invalid stored block lengths
too many length or distance symbols
invalid code lengths set
invalid bit length repeat
invalid literal/lengths set
invalid distances set
incorrect data check
Out of memory while allocating output buffer
Out of memory while allocating input buffer
Out of memory while allocating z_stream
Out of memory while allocating workspace
Not a gzip file
header error
read error
uncompression error

I got no idea. damn.

**Comment by ts-kris** [comment]
Sorry to hear you are still having issues.

First, note that zImage is compressed in such a way that it is not easy to decompress it outside of executing it. Therefore using strings to find what version it is is likely to not give much detail.

Second, if you are using a TS-7600 with a TS-752, be sure to set the jumpers to the correct settings. The TS-7600 contains a bootable SPI flash, as does the TS-752. Check the initial bootup output on the serial console to see what the unit booted from. Set the jumpers based on this table to ensure its booting to SD: https://docs.embeddedts.com/TS-7600#Booting_up_the_board

Note that, even when set to boot from SPI flash, this still uses the SD card for Debian. These jumpers affect where the kernel and initramfs are loaded from.

**Comment by FOSSBOSS** [comment]
Ive tried it with the 7600-4600 version git repo, and the git checkout
linux-3.14.79-7600-4600
Ive tried it applying the
*patch -p1 < install_bootstream-newer-fdisk.patch*
despite not having seen any indication of that issue.
attached is my uart connection of the sd card boot
here is my output of
tshwctl info

model=0x7600
submodel=0x0
revision=0x4
bootmode=0x0
fpga_pn=LFXP25E
resetsw_en=0x1

**Comment by ts-kris** [comment]
It would appear that you are indeed booting to SD. I'll set up a test to run through the full instructions including a boot test of a TS-7600. However that may be a few days for me to allocate time for. Can you please follow up in the support ticket you have open with us for this as that allows us to better track details over time.
